// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEt6HvRNhcUvduePK-6WlR51zOlxHV-Z4',
    appId: '1:9874797301:web:a70d69e51417721df04bbc',
    messagingSenderId: '9874797301',
    projectId: 'know-your-company-b2720',
    authDomain: 'know-your-company-b2720.firebaseapp.com',
    storageBucket: 'know-your-company-b2720.firebasestorage.app',
    measurementId: 'G-6384XCYTG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6kqMPgVkcC4STLid4QHWotFPoCYV1nTM',
    appId: '1:9874797301:android:b7d7585a060f0e64f04bbc',
    messagingSenderId: '9874797301',
    projectId: 'know-your-company-b2720',
    storageBucket: 'know-your-company-b2720.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEt6HvRNhcUvduePK-6WlR51zOlxHV-Z4',
    appId: '1:9874797301:web:5530a4dd35dbc030f04bbc',
    messagingSenderId: '9874797301',
    projectId: 'know-your-company-b2720',
    authDomain: 'know-your-company-b2720.firebaseapp.com',
    storageBucket: 'know-your-company-b2720.firebasestorage.app',
    measurementId: 'G-853SLK605M',
  );
}
